---
- hosts: localhost

  tasks:
    - name: Create pagerduty maintenance window
      community.general.pagerduty:
        hours: "{{ hours }}"
        minutes: "{{ minutes }}"
        state: running
        token: "{{ api_token }}"
        service: "{{ service_id }}"
        requester_id: "{{ requester_user_id }}"
        desc: "{{ desc }}"