---
- hosts: localhost

  tasks:
    - name: Create pagerduty maintenance window
      community.general.pagerduty:
        hours: 0
        minutes: 5
        state: running
        token: {{ api_token }}
        service: {{ service_id }}
        requester_id: {{ requester_user_id }}
        # token: u+PRndWfgyC_EBDz1vyw
        # service: P77YHJX
        # requester_id: PYSN9IH